config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get 'home/about'
  devise_for :users

  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
  	resource :favorite, only: [:create, :destroy]
  	resource :book_comments, only: [:create,:destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    member do
     get :follows, :followers
    end
  end

  resources :relationships, only: [:create,:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
    has_many :favorites, dependent: :destroy
    def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end
    has_many :book_comments, dependent: :destroy

	validates :title , presence: true
	validates :body, presence: true, length: { maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :book

	validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end


  validates :name, presence: true,  length: { minimum: 2, maximum: 20}
  validates :introduction, length: { maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

	#sign inした後の遷移先指定
	def after_sign_in_path_for(resource)
		user_path(resource)
	end
	#log outした後の遷移先指定
	def after_sign_out_path_for(resource)
      root_path
    end

   protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
		devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
	end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
	before_action :authenticate_user!

	def create
		@book = Book.find(params[:book_id])
		@book_comment = current_user.book_comments.new(book_comment_params)
		# コメントをしている本のIDが、本のIDと一緒だったら
		@book_comment.book_id = @book.id
		# コメントを保存
		@book_comment.save
		# 同じページに戻る
		redirect_back(fallback_location: root_path)
	end

	def destroy
		@book_comment = BookComment.find(params[:book_id])
		# コメントを削除
		@book_comment.destroy
		#同じページに戻る
		redirect_back(fallback_location: root_path)
	end

	private
	def book_comment_params
		params.require(:book_comment).permit(:comment)
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :guard, only: [:edit]

  def index
  	@book = Book.new
  	@books = Book.all
    @user = User.find(current_user.id)
  end

  def create
  	@book = Book.new(book_params)
  	@book.user_id = current_user.id
  	if @book.save
  	redirect_to book_path(@book.id), notice: "You have creatad book successfully."
    else
    @books = Book.all
    @user = User.find(current_user.id)
    render action: :index
    end
  end

  def show
  	@book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
   if @book.update(book_params)
    redirect_to book_path(@book.id), notice: "You have updated book successfully."
   else
    @books = Book.all
    render "edit"
   end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path, notice: "Book was successfully destroyed."
  end

  private

  def guard
    book = Book.find(params[:id])
    if book.user != current_user
      redirect_to books_path
    end
  end

  def book_params
  	params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	def create
		book = Book.find(params[:book_id])
		favorite = current_user.favorites.new(book_id: book.id)
		favorite.save
		redirect_back(fallback_location: root_path)
	end

	def destroy
		book = Book.find(params[:book_id])
		favorite = current_user.favorites.find_by(book_id: book.id)
		favorite.destroy
		redirect_back(fallback_location: root_path)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  before_action :set_user

  def create
    following = current_user.follow(@user)
    if following.save
      flash[:success] = 'ユーザーをフォローしました'
      redirect_back(fallback_location: root_path)
    else
      flash.now[:alert] = 'ユーザーのフォローに失敗しました'
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    following = current_user.unfollow(@user)
    if following.destroy
      flash[:success] = 'ユーザーのフォローを解除しました'
      redirect_back(fallback_location: root_path)
    else
      flash.now[:alert] = 'ユーザーのフォロー解除に失敗しました'
      redirect_back(fallback_location: root_path)
    end
  end

  private
  def set_user
    @user = User.find(params[:follow_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :guard, only: [:edit]

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
  	@user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  def follows
    @user = User.find(params[:id])
    @users = @user.followings
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
  end

private

  def guard
    user = User.find(params[:id])
    if user != current_user
      redirect_to user_path(current_user)
    end
  end

  def user_params
    params.require(:user).permit(:name, :profile_image ,:introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_new.html.erb
<h2>New book</h2>

<%= form_for(book) do |f| %>
 <div class="field row">
  <label class="control-label">Title</label><br>
  <%= f.text_field :title, class: "col-xs-12 book_title" %>
  <br>
 </div>

 <div class="field row">
  <label class="control-label">Opinion</label><br>
  <%= f.text_area :body, class: "col-xs-12 book_body" %>
  <br>
 </div>

 <div class="actions row">
  <%= f.submit "Create Book", class: "btn btn-primary col-xs-12" %>
 </div>

<% end %>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
   <h3>
    <%= @book.errors.count %>errors prohibited this book from being saved:
   </h3>
   <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
   </ul>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1>Editing Book</h1>

      <%= form_for(@book) do |f| %>
        <div class="field row">
          <h4>Title</h4>
          <%= f.text_field :title, class: "col-xs-12 book_title"%>
        </div>
        <div class="field row">
          <h4>Opinion</h4>
          <%= f.text_area :body, class: "col-xs-12 book_body" %>
          <br>
        </div>
        <div class="actions row">
          <%= f.submit "Update Book" ,class: "btn btn-primary col-xs-12" %>
          <br>
        </div>
      <% end %>

       <%= link_to 'Show', book_path %>
       ｜
      　<%= link_to 'Back', books_path  %>
      <div class="col-md-3"></div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class='container'>
  <div class='row'>
      <% if @book.errors.any? %>
       <h3>
        <%= @book.errors.count %>errors prohibited this book from being saved:
       </h3>
       <ul>
        <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
       </ul>
    <% end %>
  </div>


  <div class='row'>
    <div class='col-xs-3'>

      <%= render 'users/info', user: @user %>

      <h2>New book</h2>

      <%= form_for(@book) do |f| %>
       <div class="field row">
        <label class="control-label">Title</label><br>
        <%= f.text_field :title, class: "col-xs-12 book_title" %>
        <br>
       </div>

       <div class="field row">
        <label class="control-label">Opinion</label><br>
        <%= f.text_area :body, class: "col-xs-12 book_body" %>
        <br>
       </div>

       <div class="field row">
        <%= f.submit "Create Book", class: "btn btn-primary btn-block " %>
       </div>
      <% end %>
    </div>

    <div class="col-xs-9">
      <!-- Books一覧 -->
      <h2>Books</h2>
      <table class="table">
        <thead>
            <tr>
             <th></th>
             <th>Title</th>
             <th>Opinion</th>
             <th colspan="3"></th>
            </tr>
        </thead>
    	  <tbody>
    	  <% @books.each do |book| %>
    	    <tr>
    	     <td>
            <%= link_to user_path(book.user) do %>
              <%= attachment_image_tag book.user,:profile_image, size:'60x60',format:'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg" %>
            <% end %>
           </td>
      		 <td><%= link_to book.title,book_path(book.id) %></td>
      		 <td><%= book.body %></td>

           <!-- いいねの表示 -->
            <td>
            <% if book.favorited_by?(current_user) %>
               <%= link_to book_favorite_path(book),method: :delete do %>
               <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
               <%= book.favorites.count %>
               <% end %>
            <% else %>
               <%= link_to book_favorite_path(book),method: :post do %>
               <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
               <%= book.favorites.count %>
               <% end %>
            <% end %>
            </td>
            <!-- /いいねの表示 -->

            <!-- コメント数の表示 -->
            <td>
              コメント数：<%= book.book_comments.count %>
            </td>
            <!-- /コメント数の表示 -->
    		  </tr>
    	  <% end %>
    	  </tbody>
      </table>
      <!-- /Books一覧 -->
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <div class="row">
    <div class='col-xs-3'>
     <%= render 'users/info', user: @user %>
	 <%= render 'books/new', book: Book.new %>
	</div>

    <div class="col-xs-9">
	  <h3>Book detail</h3>
	    <table class="table">
		    <tbody>
				<tr>
				 <td>
				  <%= link_to user_path(@user.id) do %>
				 	<%= attachment_image_tag @user,:profile_image, size:'100x100', fallback: "no_image.jpg" %><br>
				 	<%= @user.name %>
				  <% end %>
				 	</td>
				 <td><%= @book.title %></td>
				 <td><%= @book.body %></td>

				 <!-- いいねの表示 -->
				 <td>
		            <% if @book.favorited_by?(current_user) %>
		               <%= link_to book_favorite_path(@book),method: :delete do %>
		               <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
		               <%= @book.favorites.count %>
		               <% end %>
		            <% else %>
		               <%= link_to book_favorite_path(@book),method: :post do %>
		               <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
		               <%= @book.favorites.count %>
		               <% end %>
		            <% end %>
		         </td>
				 <!-- /いいねの表示 -->
	             <!-- コメント数の表示 -->
	             <td>
	              コメント数：<%= @book.book_comments.count %>
	             </td>
	             <!-- /コメント数の表示 -->

				 <% if @book.user_id == current_user.id %>
				 <td><%= link_to "Edit", edit_book_path(@book.id),class: "btn-sm btn-success" %> </td>
				 <td><%= link_to "Destroy", book_path(@book.id), method: :delete,  "data-confirm" => "本当に削除しますか？"  ,class: "btn-sm btn-danger" %></td>
				 <% end %>
				 </td>
				</tr>

				<!-- コメント一覧の表示 -->
				<% @book.book_comments.each do |book_comment| %>
				<tr>
				 <td style="border: none;">
				  <%= link_to user_path(book_comment.user.id) do %>
				 	<%= attachment_image_tag book_comment.user,:profile_image, size:'50x50',　fallback: "no_image.jpg" %>
				 	<%= book_comment.user.name %>
				  <% end %>
				 </td>
				 <td style="border: none;">
				 	 <%= book_comment.comment %>
				 </td>
				 <% if book_comment.user == current_user %>
				 <td style="border: none;">
				 	<%= link_to "Destroy",book_book_comments_path(book_comment.id),method: :delete, "data-confirm" => "本当に削除しますか？" ,class: "btn-sm btn-danger" %>
				 </td>
				 <% end %>
				</tr>
				<% end %>
				<!-- /コメント一覧の表示 -->
		    </tbody>
		</table>

		<!-- コメント入力欄の表示 -->
		<%= form_for [@book,@book_comment] do |f| %>
			<div class="row">
				<div class="col-sm-10">
					<%= f.text_area :comment, rows:'5', class: "form-control" %>
					<%= f.submit '送信' %>
				</div>
			</div>
		<% end %>
		<!-- /コメント入力欄の表示 -->
    </div>
  </div>
</div>

app/views/home/about.html.erb
<h1>Welcome to <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>!</h1>

app/views/home/top.html.erb
<div class="row">
  <div class='top-message col-md-offset-3 col-md-6'>
    <h1>welcome to <span class='glyphicon glyphicon-book'><strong>Bookers</strong>  !!</h1>
          <p>In  <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>, </p>
          <p>you can share and exchange  your opinions , inpressions , and emotions</p>
          <p> about varioius books!</p>

    <div class="btn-wrapper">
      <div class="row">
         <p><%= link_to 'Log in',new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
      </div>
      <div class="row">
        <p><%= link_to 'Sign Up',new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
      </div>
    </div>
   </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class='nav navbar-nav navbar-left'>
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <li class=""><%= link_to ' Home', user_path(current_user.id) , class: "glyphicon glyphicon-home home"%></li>
            <li class=""><%= link_to ' Users', users_path, class: "glyphicon glyphicon-user users" %></li>
            <li class=""><%= link_to ' Books', books_path, class: "glyphicon glyphicon-book"  %></li>
            <li class=""><%= link_to ' logout', destroy_user_session_path, method: :delete,class: "glyphicon glyphicon-log-out"  %></li>

            <% else %>

            <li class=""><%= link_to ' Home', root_path, class: 'glyphicon glyphicon-home' %></li>
            <li class=""><%= link_to ' About', home_about_path, class: 'glyphicon glyphicon-link' %></li>
            <li class=""><%= link_to ' Sign up', new_user_registration_path,class: "glyphicon glyphicon-edit"  %></li>
            <li class=""><%= link_to ' login', new_user_session_path,class: "glyphicon glyphicon-log-in"  %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

    </div>
    <%= yield %>
    </div>

    <footer>
      <div class='container'>
        <div class='row'>
          <div class='col-xs-3 col-xs-offset-9'>
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
    
  </body>
</html>

app/views/users/_info.html.erb
<h2>User info</h2>

<div>
 <%= attachment_image_tag user, :profile_image, size:'100x100', format:'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg" %>
</div>
<table class="table">
 <tbody>

  <tr>
   <th>name</th>
   <th><%= user.name %></th>
  </tr>

  <tr>
   <th>introduction</th>
   <th><%= user.introduction %></th>
  </tr>

  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, follows_user_path(user) %></th>
  </tr>

  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, followers_user_path(user) %></th>
  </tr>
 </tbody>
</table>

<div class='row'>
  <% unless current_user == user %>
      <% if current_user.following?(user) %>
        <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
          <%= hidden_field_tag :follow_id, user.id %>
          <%= f.submit 'フォロー外す', class: 'btn btn-danger' %>
        <% end %>
      <% else %>
        <%= form_for(current_user.relationships.build) do |f| %>
          <%= hidden_field_tag :follow_id, user.id %>
          <%= f.submit 'フォローする', class: 'btn btn-success' %>
        <% end %>
      <% end %>
    <% end %>

  <% if user == current_user %>
   <%= link_to '', edit_user_path(current_user.id),class: "col-xs-12 btn btn-block btn-default glyphicon glyphicon-wrench edit_user_#{current_user.id}" %>
  <% end %>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>User info</h1>

<% if @user.errors.any? %>
   <h3>
    <%= @user.errors.count %>errors prohibited this book from being saved:
   </h3>
   <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
   </ul>
<% end %>

<%= form_for(@user) do |f| %>

<div class="field">

 <label for="user_name">Name</label>
 <%= f.text_field :name %>
 <br>
 <label for="user_image">image</label>
 <%= f.attachment_field :profile_image %>
 <br>
 <label for="user_introduction">introduction</label>
 <%= f.text_area :introduction %>

 <%= f.submit 'Update User' %>

</div>
<% end %>

app/views/users/followers.html.erb
<div class="container">
	<div class="row">
		<h1>Follower Users</h1>
	</div>
	<div class="row">
		<table class="table">
            <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th></th>
              <th colspan="3"></th>
            </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td>
                    <a><%= attachment_image_tag user, :profile_image, size: "60x60", format: 'jpeg' , class: "pull-left profile-thumb", fallback: "no_image.jpg" %></a>
                  </td>
                  <td>
                    <%= user.name %>
                  </td>
                  <td>
                    フォロー数：<%= user.followings.count %>
                  </td>
                  <td>
                    フォロワー数：<%= user.followers.count %>
                  </td>
                  <td>
                    <% unless current_user == user %>
                      <% if current_user.following?(user) %>
                        <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
                          <%= hidden_field_tag :follow_id, user.id %>
                          <%= f.submit 'フォロー外す', class: 'btn btn-danger' %>
                        <% end %>
                      <% else %>
                        <%= form_for(current_user.relationships.build) do |f| %>
                          <%= hidden_field_tag :follow_id, user.id %>
                          <%= f.submit 'フォローする', class: 'btn btn-primary' %>
                        <% end %>
                      <% end %>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to "Show", user_path(user.id) %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
	</div>
</div>

app/views/users/follows.html.erb
<div class="container">
	<div class="row">
		<h1>Follow Users</h1>
	</div>
	<div class="row">
		<table class="table">
            <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th></th>
              <th colspan="3"></th>
            </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td>
                    <a><%= attachment_image_tag user, :profile_image, size: "60x60", format: 'jpeg' , class: "pull-left profile-thumb", fallback: "no_image.jpg" %></a>
                  </td>
                  <td>
                    <%= user.name %>
                  </td>
                  <td>
                    フォロー数：<%= user.followings.count %>
                  </td>
                  <td>
                    フォロワー数：<%= user.followers.count %>
                  </td>
                  <td>
                    <% unless current_user == user %>
                      <% if current_user.following?(user) %>
                        <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
                          <%= hidden_field_tag :follow_id, user.id %>
                          <%= f.submit 'フォロー外す', class: 'btn btn-danger' %>
                        <% end %>
                      <% else %>
                        <%= form_for(current_user.relationships.build) do |f| %>
                          <%= hidden_field_tag :follow_id, user.id %>
                          <%= f.submit 'フォローする', class: 'btn btn-success' %>
                        <% end %>
                      <% end %>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to "Show", user_path(user.id) %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
      <div class="row">
        <div class="col-xs-3">
          <%= render 'users/info', user: @user %>
	      <%= render 'books/new', book: @book %>
        </div>
        <div class="col-xs-9">
          <h2>Users</h2>
          <table class="table">
            <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th></th>
              <th colspan="3"></th>
            </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td>
                    <a><%= attachment_image_tag user, :profile_image, size: "60x60", format: 'jpeg' , class: "pull-left profile-thumb", fallback: "no_image.jpg" %></a>
                  </td>
                  <td>
                    <%= user.name %>
                  </td>
                  <td>
                    <%= link_to "Show", user_path(user.id) %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <%= render 'users/info', user: @user %>
      <%= render 'books/new', book: @book %>
    </div>
   <div class="col-xs-9">
      <h2>Books</h2>
      <table class="table table-striped">
        <thead>
         <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
         </tr>
        </thead>
        <tbody>
        <% @books.each do |book| %>
          <tr>
           <td>
            <%= link_to  user_path(@user.id) do %>
             <%= attachment_image_tag @user, :profile_image, size: "60x60", format: 'jpeg', class: "pull-left profile-thumb", fallback: "no_image.jpg" %>
            <% end %>
           </td>
           <td><%= link_to book.title, book_path(book) %></td>
           <td><%= book.body %></td>
           <td>コメント数：<%= book.book_comments.count %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>